[tool.poetry]
name = "test_poetry"
version = "0.1.0"
description = ""
authors = ["Corentin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
